#   Make sure that mysql is installed prior to ruby mysql gem
#   In Linux terminal (using Ubuntu 8.10) command this:
##   >>$ sudo apt-get install libmysqlclient15-dev
#   Answer yest to install package, and then from prompt type:
#    >>$ sudo gem install mysql
#   This will install the current mysql gem version 2.7

development:
  adapter: mysql
  database: farmers 
  username: jkray
  password: mind1024

test:
  adapter: mysql
  database: farmers
  username: jkray
  password: mind1024

# For server, database names and mysql access differ
production:
  adapter: mysql
  database: justink_farmers
  username: justink
  password: mind1024
